"use client";

import { useEffect, useMemo, useState } from "react";

const money = (n: number | string, currency = "IDR") => new Intl.NumberFormat("id-ID", { style: "currency", currency, maximumFractionDigits: 2 }).format(Number(n || 0));
const num = (n: number | string) => Number(n || 0).toLocaleString("id-ID", { maximumFractionDigits: 6 });
const today = () => new Date().toISOString().slice(0, 10);

type Data = any;

export default function InvestmentDashboard() {
  const [data, setData] = useState<Data | null>(null);
  const [tab, setTab] = useState("overview");
  const [busy, setBusy] = useState(false);
  const [message, setMessage] = useState("");
  const [provider, setProvider] = useState({ name: "", countryCode: "ID", websiteUrl: "" });
  const [account, setAccount] = useState({ providerId: "", name: "", accountType: "CASH", currencyId: "", createCashAccount: true });
  const [asset, setAsset] = useState({ symbol: "", name: "", assetType: "STOCK", countryCode: "ID", currencyId: "", unitName: "share", purity: "" });
  const [trade, setTrade] = useState({ accountId: "", assetId: "", transactionType: "BUY", quantity: "", unitPrice: "", feeAmount: "", taxAmount: "", otherCharges: "", fundingCashAccountId: "", fundingWalletId: "", date: today() });
  const [cash, setCash] = useState({ cashAccountId: "", amount: "", sourceWalletId: "", destinationWalletId: "", date: today(), mode: "deposit" });
  const [income, setIncome] = useState({ accountId: "", assetId: "", type: "DIVIDEND", amount: "", destinationCashAccountId: "", destinationWalletId: "", date: today() });
  const [price, setPrice] = useState({ holdingId: "", price: "" });
  const [calculator, setCalculator] = useState({ quantity: "", acquisitionCost: "", sellFeeRatePct: "0", sellTaxRatePct: "0", sellFixedFee: "0", otherSellCosts: "0", result: "" });

  const load = async () => { const r = await fetch("/api/investments", { cache: "no-store" }); const j = await r.json(); if (!r.ok) throw new Error(j.error); setData(j); };
  useEffect(() => { load().catch(e => setMessage(e.message)); }, []);

  const run = async (body: any) => { setBusy(true); setMessage(""); try { const r = await fetch("/api/investments", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const j = await r.json(); if (!r.ok) throw new Error(j.error); await load(); setMessage("Saved successfully."); return j; } catch (e) { setMessage(e instanceof Error ? e.message : "Operation failed."); throw e; } finally { setBusy(false); } };

  const currencies = data?.currencies ?? [];
  const wallets = data?.wallets ?? [];
  const providers = data?.providers ?? [];
  const accounts = data?.accounts ?? [];
  const assets = data?.assets ?? [];
  const holdings = data?.holdings ?? [];
  const cashAccounts = data?.cashAccounts ?? [];
  const transactions = data?.transactions ?? [];
  const summary = data?.summary;
  const providerRules = useMemo(() => providers.flatMap((p: any) => (p.feeRules || []).map((r: any) => ({ ...r, providerName: p.name }))), [providers]);

  const submitProvider = async (e: React.FormEvent) => { e.preventDefault(); const p = await run({ action: "provider.create", ...provider }); setProvider({ name: "", countryCode: "ID", websiteUrl: "" }); };
  const submitAccount = async (e: React.FormEvent) => { e.preventDefault(); await run({ action: "account.create", ...account }); setAccount({ ...account, name: "" }); };
  const submitAsset = async (e: React.FormEvent) => { e.preventDefault(); await run({ action: "asset.create", ...asset, purity: asset.purity ? Number(asset.purity) : undefined }); setAsset({ ...asset, symbol: "", name: "" }); };
  const submitCash = async (e: React.FormEvent) => { e.preventDefault(); await run({ action: cash.mode === "deposit" ? "cash.deposit" : "cash.withdraw", ...cash, amount: Number(cash.amount), date: new Date(cash.date).toISOString() }); setCash({ ...cash, amount: "" }); };
  const submitTrade = async (e: React.FormEvent) => { e.preventDefault(); await run({ action: "transaction.create", ...trade, quantity: Number(trade.quantity), unitPrice: Number(trade.unitPrice), feeAmount: Number(trade.feeAmount || 0), taxAmount: Number(trade.taxAmount || 0), otherCharges: Number(trade.otherCharges || 0), transactionDate: new Date(trade.date).toISOString() }); setTrade({ ...trade, quantity: "", unitPrice: "", feeAmount: "", taxAmount: "", otherCharges: "" }); };
  const submitIncome = async (e: React.FormEvent) => { e.preventDefault(); await run({ action: "income.create", ...income, amount: Number(income.amount), date: new Date(income.date).toISOString() }); setIncome({ ...income, amount: "" }); };
  const submitPrice = async (e: React.FormEvent) => { e.preventDefault(); await run({ action: "holding.price", holdingId: price.holdingId, price: Number(price.price), date: new Date().toISOString() }); setPrice({ holdingId: "", price: "" }); };
  const calcBreakEven = async () => { const j = await run({ action: "break-even", ...calculator, quantity: Number(calculator.quantity), acquisitionCost: Number(calculator.acquisitionCost), sellFeeRatePct: Number(calculator.sellFeeRatePct), sellTaxRatePct: Number(calculator.sellTaxRatePct), sellFixedFee: Number(calculator.sellFixedFee), otherSellCosts: Number(calculator.otherSellCosts) }); setCalculator({ ...calculator, result: j.price }); };

  if (!data) return <div className="min-h-screen p-8 text-slate-300">Loading Investments…</div>;

  const field = "w-full rounded-xl border border-white/10 bg-[#0d141e] px-3 py-2.5 text-sm text-slate-100 outline-none focus:border-emerald-400/50";
  const panel = "rounded-2xl border border-white/10 bg-[#0b121b] p-5";
  const btn = "rounded-xl bg-emerald-400 px-4 py-2.5 text-sm font-bold text-[#06110c] transition hover:bg-emerald-300 disabled:opacity-50";

  return <div className="min-h-screen px-5 py-7 text-slate-100 lg:px-8">
    <div className="mx-auto max-w-[1400px]">
      <div className="mb-7 flex flex-wrap items-end justify-between gap-4">
        <div><p className="text-[10px] font-bold uppercase tracking-[0.2em] text-emerald-400">Wealth</p><h1 className="mt-1 text-3xl font-black tracking-tight">Investments</h1><p className="mt-1 text-sm text-slate-500">Cash, holdings, performance and real net sell analysis.</p></div>
        <div className="flex gap-2">{["overview", "accounts", "activity", "manage"].map(x => <button key={x} onClick={() => setTab(x)} className={`rounded-xl px-4 py-2 text-xs font-bold uppercase tracking-wide ${tab === x ? "bg-white/10 text-white" : "text-slate-500 hover:bg-white/5"}`}>{x}</button>)}</div>
      </div>
      {message && <div className="mb-5 rounded-xl border border-emerald-400/20 bg-emerald-400/5 px-4 py-3 text-sm text-emerald-300">{message}</div>}

      {tab === "overview" && <>
        <div className="grid gap-4 md:grid-cols-4">
          <div className={`${panel} md:col-span-2`}><p className="text-xs font-semibold text-slate-500">Total Investment Value</p><p className="mt-2 text-3xl font-black">{money(summary.totalInvestmentValue)}</p><p className="mt-2 text-sm text-emerald-400">{money(summary.unrealized)} · {Number(summary.returnPct).toFixed(2)}% unrealized</p></div>
          <div className={panel}><p className="text-xs text-slate-500">Invested</p><p className="mt-2 text-2xl font-black">{money(summary.totalValue)}</p><p className="mt-1 text-xs text-slate-600">Cost basis {money(summary.totalCost)}</p></div>
          <div className={panel}><p className="text-xs text-slate-500">Investment Cash</p><p className="mt-2 text-2xl font-black">{money(summary.totalCash)}</p><p className="mt-1 text-xs text-slate-600">RDN / provider cash</p></div>
        </div>
        <div className="mt-5 grid gap-5 lg:grid-cols-[1.4fr_.9fr]">
          <section className={panel}><div className="mb-4 flex items-center justify-between"><h2 className="font-bold">Holdings</h2><button onClick={() => setTab("activity")} className="text-xs text-emerald-400">View activity →</button></div>{holdings.length === 0 ? <p className="py-10 text-center text-sm text-slate-600">No holdings yet. Add an account and asset, then record a buy.</p> : <div className="space-y-2">{holdings.map((h: any) => <div key={h.id} className="grid grid-cols-[1fr_auto] gap-3 rounded-xl border border-white/5 bg-[#0d141e] p-4 md:grid-cols-[1.4fr_1fr_1fr_1fr]"><div><p className="font-bold">{h.asset.symbol || h.asset.name}</p><p className="text-xs text-slate-500">{h.account.provider.name} · {num(h.quantity)} {h.asset.unitName}</p></div><div><p className="text-xs text-slate-600">Cost</p><p className="text-sm font-semibold">{money(h.costBasis, h.asset.currency.code)}</p></div><div><p className="text-xs text-slate-600">Value</p><p className="text-sm font-semibold">{money(h.marketValue, h.asset.currency.code)}</p></div><div className="text-right"><p className="text-xs text-slate-600">P/L</p><p className={`text-sm font-bold ${Number(h.gain) >= 0 ? "text-emerald-400" : "text-rose-400"}`}>{money(h.gain, h.asset.currency.code)}</p><p className="text-[11px] text-slate-500">{Number(h.returnPct).toFixed(2)}%</p></div></div>)}</div>}</section>
          <section className={panel}><h2 className="mb-4 font-bold">Provider Cash / RDN</h2>{cashAccounts.length === 0 ? <p className="py-10 text-sm text-slate-600">No investment cash accounts.</p> : <div className="space-y-2">{cashAccounts.map((c: any) => <div key={c.id} className="rounded-xl border border-white/5 bg-[#0d141e] p-4"><div className="flex justify-between"><div><p className="font-bold">{c.account.provider.name}</p><p className="text-xs text-slate-500">{c.account.name} · {c.account.currency.code}</p></div><p className="font-black">{money(c.balance, c.account.currency.code)}</p></div></div>)}</div>}</section>
        </div>
        <section className={`${panel} mt-5`}><h2 className="mb-4 font-bold">Sell Analysis</h2><div className="grid gap-3 md:grid-cols-6"><input className={field} placeholder="Quantity" value={calculator.quantity} onChange={e => setCalculator({ ...calculator, quantity: e.target.value })}/><input className={field} placeholder="Cost basis" value={calculator.acquisitionCost} onChange={e => setCalculator({ ...calculator, acquisitionCost: e.target.value })}/><input className={field} placeholder="Sell fee %" value={calculator.sellFeeRatePct} onChange={e => setCalculator({ ...calculator, sellFeeRatePct: e.target.value })}/><input className={field} placeholder="Sell tax %" value={calculator.sellTaxRatePct} onChange={e => setCalculator({ ...calculator, sellTaxRatePct: e.target.value })}/><input className={field} placeholder="Fixed costs" value={calculator.sellFixedFee} onChange={e => setCalculator({ ...calculator, sellFixedFee: e.target.value })}/><button className={btn} disabled={busy} onClick={calcBreakEven}>Calculate break-even</button></div>{calculator.result && <div className="mt-4 rounded-xl bg-emerald-400/5 p-4"><p className="text-xs text-slate-500">Minimum sell price for Net Realized P/L = 0</p><p className="mt-1 text-2xl font-black text-emerald-300">{money(calculator.result)}</p></div>}</section>
      </>}

      {tab === "accounts" && <div className="grid gap-5 md:grid-cols-2">{accounts.map((a: any) => <div className={panel} key={a.id}><div className="flex justify-between"><div><p className="font-black">{a.name}</p><p className="text-xs text-slate-500">{a.provider.name} · {a.accountType} · {a.currency.code}</p></div><p className="text-xs text-slate-500">{a.cashAccount ? money(a.cashAccount.balance, a.currency.code) : "Portfolio only"}</p></div><div className="mt-4 grid gap-2 sm:grid-cols-2">{holdings.filter((h: any) => h.accountId === a.id).map((h: any) => <div key={h.id} className="rounded-xl border border-white/5 bg-[#0d141e] p-3"><p className="font-bold">{h.asset.symbol || h.asset.name}</p><p className="text-xs text-slate-500">{num(h.quantity)} {h.asset.unitName}</p><p className="mt-1 text-sm">{money(h.marketValue, a.currency.code)}</p></div>)}</div></div>)}</div>}

      {tab === "activity" && <div className={panel}><h2 className="mb-4 font-bold">Investment Activity</h2><div className="divide-y divide-white/5">{transactions.map((t: any) => <div key={t.id} className="grid gap-2 py-4 md:grid-cols-[110px_130px_1fr_auto] md:items-center"><p className="text-xs text-slate-500">{new Date(t.transactionDate).toLocaleDateString("id-ID")}</p><p className="text-xs font-bold uppercase text-emerald-400">{t.transactionType}</p><div><p className="font-semibold">{t.asset.symbol || t.asset.name}</p><p className="text-xs text-slate-500">{t.account.provider.name} · {num(t.quantity)} {t.asset.unitName}</p></div><div className="text-right"><p className="font-bold">{money(t.netCashAmount, t.currencyId === "" ? "IDR" : "IDR")}</p><p className="text-[11px] text-slate-600">fee {money(t.feeAmount)}</p></div></div>)}</div></div>}

      {tab === "manage" && <div className="grid gap-5 lg:grid-cols-2">
        <section className={panel}><h2 className="mb-4 font-bold">Add Provider</h2><form onSubmit={submitProvider} className="space-y-3"><input className={field} required placeholder="Provider e.g. IndoPremier" value={provider.name} onChange={e => setProvider({ ...provider, name: e.target.value })}/><input className={field} placeholder="Country code" value={provider.countryCode} onChange={e => setProvider({ ...provider, countryCode: e.target.value })}/><input className={field} placeholder="Official website" value={provider.websiteUrl} onChange={e => setProvider({ ...provider, websiteUrl: e.target.value })}/><button className={btn} disabled={busy}>Add provider</button></form></section>
        <section className={panel}><h2 className="mb-4 font-bold">Add Investment Account</h2><form onSubmit={submitAccount} className="space-y-3"><select className={field} required value={account.providerId} onChange={e => setAccount({ ...account, providerId: e.target.value })}><option value="">Provider</option>{providers.map((p: any) => <option key={p.id} value={p.id}>{p.name}</option>)}</select><input className={field} required placeholder="Account name e.g. IndoPremier RDN" value={account.name} onChange={e => setAccount({ ...account, name: e.target.value })}/><select className={field} value={account.accountType} onChange={e => setAccount({ ...account, accountType: e.target.value })}><option value="CASH">Cash / RDN</option><option value="PORTFOLIO">Portfolio</option><option value="COMBINED">Combined</option></select><select className={field} required value={account.currencyId} onChange={e => setAccount({ ...account, currencyId: e.target.value })}><option value="">Currency</option>{currencies.map((c: any) => <option key={c.id} value={c.id}>{c.code}</option>)}</select><label className="flex items-center gap-2 text-xs text-slate-400"><input type="checkbox" checked={account.createCashAccount} onChange={e => setAccount({ ...account, createCashAccount: e.target.checked })}/> Create provider cash/RDN balance</label><button className={btn} disabled={busy}>Add account</button></form></section>
        <section className={panel}><h2 className="mb-4 font-bold">Add Asset</h2><form onSubmit={submitAsset} className="space-y-3"><input className={field} placeholder="Symbol e.g. BBCA" value={asset.symbol} onChange={e => setAsset({ ...asset, symbol: e.target.value })}/><input className={field} required placeholder="Asset name" value={asset.name} onChange={e => setAsset({ ...asset, name: e.target.value })}/><select className={field} value={asset.assetType} onChange={e => setAsset({ ...asset, assetType: e.target.value })}><option value="STOCK">Stock</option><option value="MUTUAL_FUND">Mutual Fund</option><option value="ETF">ETF</option><option value="BOND">Bond</option><option value="GOLD">Gold</option><option value="OTHER">Other</option></select><div className="grid grid-cols-2 gap-3"><input className={field} placeholder="Country" value={asset.countryCode} onChange={e => setAsset({ ...asset, countryCode: e.target.value })}/><select className={field} required value={asset.currencyId} onChange={e => setAsset({ ...asset, currencyId: e.target.value })}><option value="">Currency</option>{currencies.map((c: any) => <option key={c.id} value={c.id}>{c.code}</option>)}</select></div><input className={field} required placeholder="Unit: share / unit / gram" value={asset.unitName} onChange={e => setAsset({ ...asset, unitName: e.target.value })}/><button className={btn} disabled={busy}>Add asset</button></form></section>
        <section className={panel}><h2 className="mb-4 font-bold">Provider Cash / RDN</h2><form onSubmit={submitCash} className="space-y-3"><select className={field} required value={cash.cashAccountId} onChange={e => setCash({ ...cash, cashAccountId: e.target.value })}><option value="">Cash account</option>{cashAccounts.map((c: any) => <option key={c.id} value={c.id}>{c.account.provider.name} · {c.account.name}</option>)}</select><div className="flex gap-2"><button type="button" onClick={() => setCash({ ...cash, mode: "deposit" })} className={`flex-1 rounded-xl px-3 py-2 text-xs font-bold ${cash.mode === "deposit" ? "bg-emerald-400 text-[#06110c]" : "bg-white/5 text-slate-400"}`}>Deposit</button><button type="button" onClick={() => setCash({ ...cash, mode: "withdraw" })} className={`flex-1 rounded-xl px-3 py-2 text-xs font-bold ${cash.mode === "withdraw" ? "bg-rose-400 text-white" : "bg-white/5 text-slate-400"}`}>Withdraw</button></div><input className={field} required type="number" min="0" step="0.01" placeholder="Amount" value={cash.amount} onChange={e => setCash({ ...cash, amount: e.target.value })}/>{cash.mode === "deposit" ? <select className={field} value={cash.sourceWalletId} onChange={e => setCash({ ...cash, sourceWalletId: e.target.value })}><option value="">Source wallet (optional)</option>{wallets.map((w: any) => <option key={w.id} value={w.id}>{w.name} · {w.currency.code}</option>)}</select> : <select className={field} value={cash.destinationWalletId} onChange={e => setCash({ ...cash, destinationWalletId: e.target.value })}><option value="">Destination wallet (optional)</option>{wallets.map((w: any) => <option key={w.id} value={w.id}>{w.name} · {w.currency.code}</option>)}</select>}<button className={btn} disabled={busy}>Save cash movement</button></form></section>
        <section className={`${panel} lg:col-span-2`}><h2 className="mb-4 font-bold">Buy / Sell</h2><form onSubmit={submitTrade} className="grid gap-3 md:grid-cols-4"><select className={field} required value={trade.accountId} onChange={e => setTrade({ ...trade, accountId: e.target.value })}><option value="">Investment account</option>{accounts.map((a: any) => <option key={a.id} value={a.id}>{a.provider.name} · {a.name}</option>)}</select><select className={field} required value={trade.assetId} onChange={e => setTrade({ ...trade, assetId: e.target.value })}><option value="">Asset</option>{assets.map((a: any) => <option key={a.id} value={a.id}>{a.symbol || a.name}</option>)}</select><select className={field} value={trade.transactionType} onChange={e => setTrade({ ...trade, transactionType: e.target.value })}><option value="BUY">Buy</option><option value="SELL">Sell</option></select><input className={field} required type="number" min="0" step="0.000001" placeholder="Quantity" value={trade.quantity} onChange={e => setTrade({ ...trade, quantity: e.target.value })}/><input className={field} required type="number" min="0" step="0.000001" placeholder="Price" value={trade.unitPrice} onChange={e => setTrade({ ...trade, unitPrice: e.target.value })}/><input className={field} type="number" min="0" step="0.01" placeholder="Fee" value={trade.feeAmount} onChange={e => setTrade({ ...trade, feeAmount: e.target.value })}/><input className={field} type="number" min="0" step="0.01" placeholder="Tax" value={trade.taxAmount} onChange={e => setTrade({ ...trade, taxAmount: e.target.value })}/><input className={field} type="number" min="0" step="0.01" placeholder="Other charges" value={trade.otherCharges} onChange={e => setTrade({ ...trade, otherCharges: e.target.value })}/><select className={field} value={trade.fundingCashAccountId} onChange={e => setTrade({ ...trade, fundingCashAccountId: e.target.value, fundingWalletId: "" })}><option value="">Funding: provider cash</option>{cashAccounts.map((c: any) => <option key={c.id} value={c.id}>{c.account.provider.name} · {c.account.name}</option>)}</select><select className={field} value={trade.fundingWalletId} onChange={e => setTrade({ ...trade, fundingWalletId: e.target.value, fundingCashAccountId: "" })}><option value="">Or funding: wallet</option>{wallets.map((w: any) => <option key={w.id} value={w.id}>{w.name} · {w.currency.code}</option>)}</select><input className={field} type="date" value={trade.date} onChange={e => setTrade({ ...trade, date: e.target.value })}/><button className={`${btn} md:col-span-4`} disabled={busy}>Record {trade.transactionType === "BUY" ? "Purchase" : "Sale"}</button></form></section>
        <section className={panel}><h2 className="mb-4 font-bold">Dividend / Interest / Coupon</h2><form onSubmit={submitIncome} className="space-y-3"><select className={field} required value={income.accountId} onChange={e => setIncome({ ...income, accountId: e.target.value })}><option value="">Investment account</option>{accounts.map((a: any) => <option key={a.id} value={a.id}>{a.provider.name} · {a.name}</option>)}</select><select className={field} required value={income.assetId} onChange={e => setIncome({ ...income, assetId: e.target.value })}><option value="">Asset</option>{assets.map((a: any) => <option key={a.id} value={a.id}>{a.symbol || a.name}</option>)}</select><select className={field} value={income.type} onChange={e => setIncome({ ...income, type: e.target.value })}><option value="DIVIDEND">Dividend</option><option value="INTEREST">Interest</option><option value="COUPON">Coupon</option></select><input className={field} required type="number" min="0" step="0.01" placeholder="Amount" value={income.amount} onChange={e => setIncome({ ...income, amount: e.target.value })}/><select className={field} value={income.destinationCashAccountId} onChange={e => setIncome({ ...income, destinationCashAccountId: e.target.value, destinationWalletId: "" })}><option value="">Destination: provider cash</option>{cashAccounts.map((c: any) => <option key={c.id} value={c.id}>{c.account.provider.name} · {c.account.name}</option>)}</select><button className={btn} disabled={busy}>Record income</button></form></section>
        <section className={panel}><h2 className="mb-4 font-bold">Update Market Price</h2><form onSubmit={submitPrice} className="space-y-3"><select className={field} required value={price.holdingId} onChange={e => setPrice({ ...price, holdingId: e.target.value })}><option value="">Holding</option>{holdings.map((h: any) => <option key={h.id} value={h.id}>{h.asset.symbol || h.asset.name} · {h.account.provider.name}</option>)}</select><input className={field} required type="number" min="0" step="0.000001" placeholder="Current price / NAV / gram" value={price.price} onChange={e => setPrice({ ...price, price: e.target.value })}/><button className={btn} disabled={busy}>Update valuation</button></form><p className="mt-3 text-[11px] leading-relaxed text-slate-600">Price updates are intentionally manual in this first investment slice. Fee/tax rules are stored with effective dates and source labels so actual transactions remain auditable.</p></section>
      </div>}
    </div>
  </div>;
}
